package automod_legacy

// These words are listed in in alphabethical order.
var BuiltinSwearWords = map[string]bool{
	
	"b1tch":       true,
	"bastard":     true,
	"bitch":       true,
	"biatch":      true,
	"cunt":        true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        true,
	"fucks":       true,
	"nigger":      true,
	"nigga":       true,
	"slut":        true,
	"smegma":      true,
	"twat":        true,
	"asshole":     true,
	"nigger":     true,
	"nigga":     true,
	"n1gga":     true,
	"negger":     true,
	"nibba":     true,
	"niggah":     true,
	"nigguh":     true,
	"n1gg3r":     true,
	"n1gga":     true,
	"nigg4":     true,
	"retard":     true,
	"retarded":     true,
	"ret4rd":     true,
	"r3tard":     true,
	"r3t4rd":     true,
	"faggot":     true,
	"fag":     true,
	"f4g":     true,
	"f4ggot":     true,
	"fagg0t":     true,
	"tranny":     true,
	"tr4nny":     true,
	"Chloe Kirchner":     true,
	"Valentin Kornberger":     true,
	"jacob pregezier":     true,
	"maurichgasse":     true,
	"schwulette":     true,
    
}
